services:
  db:
    image: db
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1005
      POSTGRES_DB: gigigenie
    networks:
      - container_network
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gigigenie
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1005
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - container_network
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - container_network
networks:
  container_network: