services:
  db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1005
      POSTGRES_DB: manulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - container_network
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - container_network
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/manulo
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1005
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - container_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - container_network
networks:
  container_network:

volumes:
  postgres_data: