version: "3.8"

services:
  db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./backend/db/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1005
      POSTGRES_DB: gigigenie
    networks:
      - container_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gigigenie
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1005
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - container_network
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./fastapi/.env
    environment:
      DATABASE_URL: postgresql://postgres:1005@db:5432/gigigenie
    networks:
      - container_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
      - fastapi
    env_file:
      - ./frontend/.env
    networks:
      - container_network
networks:
  container_network: