spring:
  profiles:
    active: dev  # 기본적으로 dev 프로파일 사용
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

upstage:
  api:
    key: ${UPSTAGE_API_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}
