server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gigigenie
    username: postgres
    password: 1005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  props:
    jwt:
      secret-key: 1234567890123456789012345678901234567890
      access-token-expiration-period: 150
      refresh-token-expiration-period: 1440

cors:
  allowed-origins: http://localhost:3000,http://127.0.0.1:3000

fastapi:
  url: http://localhost:8000
