server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  props:
    jwt:
      secret-key: 1234567890123456789012345678901234567890
      access-token-expiration-period: 15
      refresh-token-expiration-period: 1440

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}