server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gigigenie
    username: postgres
    password: 1005
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

upstage:
  api:
    key: ${UPSTAGE_API_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}

app:
  props:
    jwt:
      secret-key: 1234567890123456789012345678901234567890
      access-token-expiration-period: 150   # 운영시, 15분, 테스트를 위해 150분
      refresh-token-expiration-period: 1440  # 24시간 60 * 24 = 1440분
