spring:
  profiles:
    active: dev  # 기본적으로 dev 프로파일 사용
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1
    key: ${GEMINI_API_KEY}

openai:
  api:
    url: https://api.openai.com/v1
    key: ${OPENAI_API_KEY}
