spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gigigenie
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

upstage:
  api:
    key: ${UPSTAGE_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}
