spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1005
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

upstage:
  api:
    key: ${UPSTAGE_API_KEY}
